version: '3'
services:
    web:    
        image: nginx:latest
        container_name: nginx
        ports:
            - "8000:80"
            - "3000:443"
        restart: always
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./web:/web"
        depends_on:
            - "mariadb"
        links:
            - "mariadb:mariadb"
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:8080"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mariadb
        restart: always
        depends_on:
            - "mariadb"
    mariadb:
        image: mariadb:latest
        container_name: mariadb
        restart: always
        environment:
            - MYSQL_DATABASE=setserver
            - MYSQL_ROOT_PASSWORD=dev
            - MYSQL_USER=dev
            - MYSQL_PASSWORD=dev
        volumes:
            - ./database/cp:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"


