version: '3'
services:
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:8080"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mariadb
        restart: always
        depends_on:
            - "mariadb"
    mariadb:
        image: mariadb:latest
        container_name: mariadb
        restart: always
        environment:
            - MYSQL_DATABASE=setserver
            - MYSQL_ROOT_PASSWORD=dev
            - MYSQL_USER=dev
            - MYSQL_PASSWORD=dev
        volumes:
            - ./database/cp:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"
