version: '3.3'
volumes:
  data:
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
    volumes:
       - ./database/cp:/docker-entrypoint-initdb.d
       - data:/var/lib/mysql
    ports:
       - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    links:
      - mariadb
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1
  api:
    build: ./app
    container_name: api
    restart: always
    ports:
      - "7000:7000"
    links:
      - "mariadb:mariadb"
    depends_on:
      - "mariadb"
      - "phpmyadmin"