version: '3.3'
volumes:
  data:
services:
  db:
    image: mariadb:latest
    container_name: db
    restart: always
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    links:
      - db
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
  api:
    build: ./app
    container_name: api
    restart: always
    links:
      - db
    ports:
      - "8000:8000"
    depends_on:
      - db
 
